;CRIAR UM SEMÁFARO 
;RED = 3SEG	YELLOW=1SEG    GREEN = 2SEG
;FOSC = 4MHZ
;UTILIZE A INTERRUPÇÃO DO TIMER1
    #INCLUDE<P16F628A.INC>
    ORG 0X00
    
    
    GOTO START
    ORG 0X04
    BANKSEL PIR1
    BCF	    PIR1,0
    DECFSZ  TEMP1,F
    RETFIE
    BANKSEL PORTB
    MOVLW   0XFF	    ;DESLIGA TODOS OS LEDS
    XORWF   PORTB,F
    ;LÓGICA PARA MUDAR O LEDS
    RLF	PORTB,F
    ;LÓGICA PARA MUDAR OS TEMPORIZADORES
    INCF	TEMPO,F
    MOVF	TEMPO,W
    SUBWF	TEMP1,W
    BTFSS	STATUS,Z
    MOVLW	TEMP2
    MOVWF	TEMPO
    SUBWF	TEMPO,W
    BTFSS	STATUS,Z
    MOVLW	TEMP3
    MOVWF	TEMPO
    RETFIE
    
    
    TEMP1 EQU 0X20
   
    
    
    START
    ;CONFIGURAR O PINOUT
    BANKSEL	PORTB
    MOVLW	B'00010000'
    MOVWF	PORTB
    BANKSEL	TRISB
    CLRF	TRISB
    ;CONFIGURAR O TIMER2
    BANKSEL	T1CON
    MOVLW	B'00110001'	;INICIALIZA TMR1, PRESCALLE 1:8 , CLK INTERNO 
    MOVWF	T1CON
    MOVLW	B'00000000'		;INICIALIZA OS TIMER COM ESSES VALORES
    MOVWF	TMR1L		;LSB
    MOVLW	B'00000000'		
    MOVWF	TMR1H		;MSB
    
    ;CONFIGURAR INTERRUPÇÃO
    BANKSEL PIE1
    MOVLW   B'11000000'	    ;INTERUPÇÃO DE PERIFÉRICOS
    MOVWF   INTCON
    MOVLW   B'00000001'	    ;INTERUPÇÃO DO TIMER1
    MOVWF   PIE1
    
    ;CONFIGURAR O POSCALLE
    MOVLW   D'2'
    MOVWF   TEMP1
    BANKSEL PORTB
    LOOP
    GOTO LOOP	    ;GERA A INTERRUPÇÃO
 
    END


