#INCLUDE<P16F628A.INC>
    ORG 0X00
    CONTA EQU 0X20
    GOTO START
    
    ORG 0X04
    BANKSEL TXREG
    BCF	    INTCON,2
    DECFSZ  CONTA,F
    RETFIE
    MOVLW   D'15'
    MOVWF   CONTA
    MOVLW   'T'
    MOVWF   TXREG
    RETFIE

    
    
    START
    ;ATIVAÇÃO DA INTERRUPÇÃO, TIMER0.
    BANKSEL	PIE1
    MOVLW	B'0001000'
    MOVWF	PIE1
    MOVLW	B'11100000'
    MOVWF	INTCON
    ; CONFIGURANDO O TIMER0, E CONFIGURANDO O I/0 DE TRISB
    BANKSEL	TRISB
    MOVLW	B'10000111'
    MOVWF	OPTION_REG
    CLRF	TRISB
    BANKSEL	PORTB
    MOVLW	D'15'
    MOVWF	CONTA
    ; CONFIGURANDO O ENVIO DE DADOS
    BANKSEL RCSTA
    MOVLW   B'10000000'
    MOVWF   RCSTA
    BANKSEL TXSTA
    MOVLW   B'00100110'
    MOVWF   TXSTA
    MOVLW   D'25'
    MOVWF   SPBRG
    
    
    FIM 
    GOTO    FIM
    END