#include<p16f628a.inc>
ORG 0X00
GOTO START
ORG 0X04
RETFIE

    
TEMP0 EQU 0X70
TEMP1 EQU 0X6F
TEMP2 EQU 0X21

START
BANKSEL TRISA	; CONFIGURO OS PINOS DO PORTA A COMO OUT
MOVLW 0X00
MOVWF TRISA
BANKSEL CMCON	; DESABITLITO O ´MÓDULO COMPARADOR
MOVLW 0X07
MOVWF CMCON
BANKSEL PORTA
MOVLW 0XFF	; CONFIGURO OS PINOS DA PORTA A PARA SAÍDA DE 5V NO INÍCIO
MOVWF PORTA
GOTO MAIN
 

MAIN
BANKSEL TRISA
BCF TRISA,0
MOVLW 0XFF ;
CALL DELAY
BSF TRISA,0
MOVLW 0XFF
CALL DELAY
GOTO MAIN


DELAY
    MOVLW 0x0A   ; Carrega o valor 10 (0x0A) em TEMP0
    MOVWF TEMP0

DELAY_LOOP0
    MOVLW 0xFF   ; Carrega o valor 255 (0xFF) em TEMP1
    MOVWF TEMP1

DELAY_LOOP1
    MOVLW 0x4D   ; Carrega o valor 77 (0x4D) em TEMP2
    MOVWF TEMP2

DELAY_LOOP2
    DECFSZ TEMP2, F   ; Decrementa TEMP2 e verifica se é zero
    GOTO DELAY_LOOP2

    DECFSZ TEMP1, F   ; Decrementa TEMP1 e verifica se é zero
    GOTO DELAY_LOOP1

    DECFSZ TEMP0, F   ; Decrementa TEMP0 e verifica se é zero
    GOTO DELAY_LOOP0

    RETURN
 
 

END


